apiVersion: v1
kind: Pod
metadata:
  name: aplicacao-noticia
spec:
  containers:
    - name: container-aplicacao
      image: danielakioteixeira/noticias-alura:v1
      ports:
        - containerPort: 80
