apiVersion: v1
kind: Pod
metadata:
  name: aplicacao-noticia
spec:
  containers:
    - name: container-aplicacao
      image: danielakioteixeira/noticias-alura:v1
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
