apiVersion: v1
kind: StatefulSet
metadata:
  name: aplicacao-sistema-statefulset
spec:
  serviceName: aplicacao-sistema-statefulset
  selector:
    matchLabels:
      name: aplicacao-sistema-pod-statefulset
  template:
    metadata:
      labels:
        name: aplicacao-sistema-pod-statefulset
    spec:
      containers:
        - name: container-aplicacao-sistema-statefulset
          image: danielakioteixeira/noticias-alura:v2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: imagens
              mountPath: /var/www//html/uploads
            - name: sessoes
              mountPath: /tmp
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: permissao-imagens
        - name: sessoes
          persistentVolumeClaim:
            claimName: permissao-sessao